site:
  title: QCDCF Documentation
  start_page: qcdcf::index.adoc

content:
  sources:
    - url: .
      start_path: src/docs
      branches: HEAD
      worktrees: true

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: build/docs/site
